# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Prog 2 Practice

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tp:
        type: choice
        description: 'TP to hand-in'
        required: true
        options:
          - tp-1
          - tp-2
          - tp-3
          - tp-4
          - tp-5
          - tp-6
          - tp-7
      publish_tps:
        type: boolean
        description: 'True if you want to hand-in, False otherwise for just running all tests'
        required: true
        default: False

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - if: github.event_name == 'push' || inputs.publish_tps == false
      name: Run All Tests
      run: |
        pytest
    - if: inputs.publish_tps == true
      name: Publish ${{ inputs.tp }}
      run: |
        pytest exercises/practice/${{ inputs.tp }} 
        if [ $? -eq 0 ]; then
          echo "${{ inputs.tp }} Successfully handed-in!"
        else
          echo "Cannot hand-in ${{ inputs.tp }} because it has errors!"
        fi
